### ISSUE TITLE
报错java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Font;

### ISSUE THREAD

**Issue by KrishuCN** [yindz/common-random#19]
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Font;
        at com.apifan.common.random.source.PersonInfoSource.<clinit>(PersonInfoSource.java:42)
        at com.apifan.common.random.source.PersonInfoSource.getInstance(PersonInfoSource.java:186)
        at top.kxxg.lvcha.ui.search.SearchFragment$initBanner$1$1.invokeSuspend(SearchFragment.kt:131)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by yindz** [comment]
Android运行时目前并不支持 awt。暂时无解。
